### ISSUE TITLE
Support for packing the whole struct with little endian without specificing it for every field

### ISSUE THREAD

**Issue by PunkS7yle** [m29h/struc-gen#6]
https://github.com/lunixbochs/struc allows you to pack while passing an option for endianess, could something similar be added to this package ?

**Comment by m29h** [comment]
If you mean options like those that can be passed to e.g. the function 
 func PackWithOptions(w io.Writer, data interface{}, options *Options) error 
I am afraid the answer is no.

The entire code generation of this library here is to generate marshal/unmarshal code that is as 'static' as possible so that the compiler can optimize it as much as possible. Any runtime options would make the generated code have additional branches making things unnecessary big and (potentially) less efficient and also reducing potential for compile-time optimization.

Why don't you just declare endianness directly on each struct tag explicitly?

If you need two variants with both big and little endian you could just declare two otherwise identical variants of your struct, one with big and one with littleendian. This would allow to type-cast between the two variants and then marshal the variant accordingly.

**Comment by PunkS7yle** [comment]
I meant something more like passing it as a flag to the code gen, like //go:generate struc-go little. As for not writing it for every field in the struct, it's due to the fact that there are cases of structs with hundreds of fields(of course you can break it down). So it's either passing endianess once or using a macro to replace in selection to add ,little" to every field.

**Comment by m29h** [comment]
The new release v0.9.3 features a "-little" command line flag. Enjoy!
